確認画面のスタイリング
zemi-team2/sake pull request #86
Opened 2021-09-21 09:11 UTC by watagit

## 🔨 Details of Changes

Figma を参考に、確認画面にスタイルを当てました

## 📸 Screenshot

<img width="375" alt="スクリーンショット 2021-09-21 18 09 30" src="https://user-images.githubusercontent.com/44804976/134144154-ce8e6eb5-b7a9-41c6-9cb4-8d0e3199a45f.png">

## ✅ Resolved Issues

- close #69 

## 🤝 Related Issues

- #69 
- #70

2021-09-21 09:14 UTC, watagit commented on frontend/src/styles/preview.css
> +  box-shadow: 0 0 30px rgba(0, 0, 0, 0.25);
ここだけ px で指定しているのが気になる

2021-09-21 16:15 UTC, mitukawa requested changes

2021-09-21 16:15 UTC, mitukawa commented on frontend/src/html/preview.html
> +        <button id="retake_button" class="button" onclick="location.href='/'">撮り直し</button>
type="button"を指定しないと`result/`に移動してしまうので、#89 で修正したけど、一応付けといてください。

2021-09-24 08:20 UTC, watagit commented
#89 がマージされ次第再度確認します！

2021-09-24 11:20 UTC, watagit commented on frontend/src/html/preview.html
>  <head>
これ

2021-09-24 11:20 UTC, watagit commented on frontend/src/styles/preview.css
> +body {
これ

2021-09-24 11:21 UTC, mitukawa approved these changes
確認しました

2021-09-24 11:22 UTC, mitukawa commented
![LGTM](https://image.lgtmoon.dev/141411)

2021-09-24 11:22 UTC, merged